services:
  postgres:
    image: postgres:17.4
    container_name: QwenPostgres
    restart: always
    environment:
      POSTGRES_USER: MeNaemS
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: users_info
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - QwenBotNetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: qwen_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - QwenBotNetwork
    depends_on:
      - postgres

networks:
  QwenBotNetwork:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: